# Generated by Django 5.2.8 on 2025-11-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telegram_exists',
            field=models.BooleanField(default=True),
        ),
    ]
