# Generated by Django 5.2.8 on 2025-11-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_telegram_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
