# Generated by Django 5.2.8 on 2025-11-25 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_message_sender_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='is_spam_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='spam_block_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='spam_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MessagingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('ai_prompt', models.TextField(blank=True, help_text='AI ga beriladigan prompt', null=True)),
                ('use_ai', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('stopped', 'Stopped')], default='draft', max_length=20)),
                ('total_contacts', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('spam_blocked_count', models.IntegerField(default=0)),
                ('delay_between_messages', models.IntegerField(default=5, help_text='Xabarlar orasidagi kutish vaqti (soniya)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('accounts', models.ManyToManyField(related_name='campaigns', to='home.telegramaccount')),
                ('contacts', models.ManyToManyField(related_name='campaigns', to='home.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Messaging Campaign',
                'verbose_name_plural': 'Messaging Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('spam_blocked', 'Spam Blocked')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.telegramaccount')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contact')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='home.messagingcampaign')),
            ],
            options={
                'verbose_name': 'Campaign Message Log',
                'verbose_name_plural': 'Campaign Message Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
