# Generated by Django 5.2.8 on 2025-11-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_telegramaccount_is_spam_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
