# Generated by Django 5.2.8 on 2025-11-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_autoreplyrule_autoreplylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoreplyrule',
            name='mark_as_read',
            field=models.BooleanField(default=True, help_text="Xabarni o'qilgan deb belgilash (double tick)"),
        ),
        migrations.AddField(
            model_name='autoreplyrule',
            name='show_typing',
            field=models.BooleanField(default=True, help_text="Typing indicator ko'rsatish"),
        ),
        migrations.AddField(
            model_name='autoreplyrule',
            name='typing_duration',
            field=models.IntegerField(default=2, help_text="Typing ko'rsatish davomiyligi (soniya)"),
        ),
    ]
