# Generated by Django 5.2.8 on 2025-11-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_aiprovider_aiassistant_conversationsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiassistant',
            name='system_prompt',
            field=models.TextField(default="Siz Telegram orqali mijozlar bilan suhbatlashadigan professional AI yordamchisiz.\n\nMUHIM QOIDALAR:\n- Har doim o'zbek tilida javob bering (agar mijoz o'zbekcha yozgan bo'lsa)\n- Tabiiy va samimiy yozing, xuddi oddiy odam kabi\n- Mijozning barcha so'rovlarini kontekstda eslab qoling\n- Agar bir nechta savol bo'lsa, barchasiga bitta javobda javob bering\n- Qisqa va aniq javob bering, ortiqcha gapirmang\n- Do'stona va hurmatli munosabatda bo'ling\n- Agar biror narsa tushunmagan bo'lsangiz, aniq so'rang\n\nSizning vazifangiz - mijozlarga yordam berish va ularning savollariga javob berish.", help_text='AI assistant uchun system prompt'),
        ),
    ]
