# Generated by Django 5.2.8 on 2025-11-27 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_conversationsummary_context_window_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="CRM nomi (masalan: 'Uy-joy CRM')", max_length=200)),
                ('crm_type', models.CharField(choices=[('custom_api', 'Custom API'), ('amocrm', 'AmoCRM'), ('bitrix24', 'Bitrix24'), ('hubspot', 'HubSpot'), ('salesforce', 'Salesforce'), ('zoho', 'Zoho CRM'), ('pipedrive', 'Pipedrive'), ('simple_json', 'Simple JSON File')], default='custom_api', max_length=50)),
                ('api_url', models.URLField(blank=True, help_text='CRM API endpoint', max_length=500, null=True)),
                ('api_key', models.CharField(blank=True, help_text='API Key/Token', max_length=500, null=True)),
                ('api_secret', models.CharField(blank=True, help_text="API Secret (agar kerak bo'lsa)", max_length=500, null=True)),
                ('field_mapping', models.JSONField(blank=True, default=dict, help_text='CRM field mapping - Telegram summary -> CRM fields')),
                ('request_template', models.JSONField(blank=True, default=dict, help_text="API so'rov template")),
                ('extraction_prompt', models.TextField(blank=True, help_text='AI ga beriluvchi prompt - suhbatdan uy talablarini JSON formatda chiqarish uchun')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRM Provider',
                'verbose_name_plural': 'CRM Providers',
            },
        ),
        migrations.CreateModel(
            name='PropertySearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(help_text='Telegram chat ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('extracted_requirements', models.JSONField(default=dict, help_text='Suhbatdan olingan talablar')),
                ('crm_request', models.JSONField(default=dict, help_text="CRM ga yuborilgan so'rov")),
                ('crm_response', models.JSONField(default=dict, help_text='CRM dan kelgan javob')),
                ('results_count', models.IntegerField(default=0, help_text='Topilgan uylar soni')),
                ('results_sent', models.BooleanField(default=False, help_text='Natijalar yuborilganmi?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('no_results', 'No Results')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crm_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to='home.crmprovider')),
                ('telegram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_searches', to='home.telegramaccount')),
            ],
            options={
                'verbose_name': 'Property Search Log',
                'verbose_name_plural': 'Property Search Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
