# Generated by Django 5.2.8 on 2025-11-27 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_crmprovider_propertysearchlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(help_text='Telegram chat ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('property_id', models.CharField(help_text='CRM da uy ID si', max_length=100)),
                ('property_data', models.JSONField(default=dict, help_text="Uy to'liq ma'lumotlari")),
                ('status', models.CharField(choices=[('interested', 'Qiziqdi'), ('rejected', 'Rad etdi'), ('viewed', "Ko'rdi")], default='viewed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.contact')),
                ('search_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='home.propertysearchlog')),
                ('telegram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_interests', to='home.telegramaccount')),
            ],
            options={
                'verbose_name': 'Property Interest',
                'verbose_name_plural': 'Property Interests',
                'ordering': ['-created_at'],
                'unique_together': {('chat_id', 'property_id')},
            },
        ),
    ]
