# Generated by Django 6.0.4 on 2026-04-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPPhoneCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('operator_name', models.CharField(blank=True, max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('tree_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('call_record_link', models.URLField(blank=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('src_num', models.CharField(blank=True, max_length=50)),
                ('dst_num', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'IP Phone Call',
                'verbose_name_plural': 'IP Phone Calls',
                'ordering': ['-timestamp'],
            },
        ),
    ]
