# Generated by Django 6.0 on 2026-04-13 05:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0004_uzbekvoiceconfiguration'),
        ('operators_analys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='STTRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('original_audio_url', models.URLField(help_text='Asl audio fayl URL manzili', max_length=1000, verbose_name='Audio URL')),
                ('transcribed_text', models.TextField(blank=True, default='', help_text="Nutqdan matnga o'girilgan natija", verbose_name='Transkripsiya qilingan matn')),
                ('api_response', models.JSONField(blank=True, help_text="To'liq API response", null=True, verbose_name='API javob')),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Rus'), ('ru-uz', "O'zbek-Rus (Aralash)")], default='uz', max_length=10, verbose_name='Til')),
                ('with_offsets', models.BooleanField(default=True, verbose_name='Vaqt offsetlari bor')),
                ('with_diarization', models.BooleanField(default=False, verbose_name="So'zlovchilar bo'lingan")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Bajarildi'), ('failed', 'Xatolik')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xatolik xabari')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Qayta ishlangan vaqt')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Davomiyligi (soniya)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Model turi')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_stt_records', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan')),
            ],
            options={
                'verbose_name': 'STT Yozuv',
                'verbose_name_plural': 'STT Yozuvlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField(blank=True, default='', help_text='AI tomonidan tahlil qilingan natija', verbose_name='AI Tahlili')),
                ('overall_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Umumiy baho (1-10)')),
                ('customer_satisfaction', models.CharField(choices=[('satisfied', 'Qoniqdi'), ('neutral', 'Neytral'), ('unsatisfied', 'Qoniqmadi'), ('unknown', "Noma'lum")], default='unknown', max_length=20, verbose_name='Mijoz qoniqishi')),
                ('key_points', models.JSONField(blank=True, null=True, verbose_name='Muhim nuqtalar')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Tavsiyalar')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Bajarildi'), ('failed', 'Xatolik')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xatolik xabari')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tahlil qilingan vaqt')),
                ('tokens_used', models.IntegerField(blank=True, null=True, verbose_name='Ishlatilgan tokenlar')),
                ('api_response', models.JSONField(blank=True, null=True, verbose_name="To'liq API javob")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.aiconfiguration', verbose_name='Ishlatilgan AI config')),
                ('analyzed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan')),
                ('stt_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='operators_analys.sttrecord', verbose_name='STT yozuv')),
            ],
            options={
                'verbose_name': 'AI Tahlil',
                'verbose_name_plural': 'AI Tahlillar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sttrecord',
            index=models.Index(fields=['content_type', 'object_id'], name='operators_a_content_8b1611_idx'),
        ),
        migrations.AddIndex(
            model_name='sttrecord',
            index=models.Index(fields=['status', 'created_at'], name='operators_a_status_b2967c_idx'),
        ),
    ]
