# Generated by Django 6.0 on 2026-04-13 06:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators_analys', '0002_sttrecord_aianalysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorAIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Konfiguratsiya nomi (masalan: Asosiy tahlil, SPIN tahlil)', max_length=255, verbose_name='Nomi')),
                ('api_provider', models.CharField(choices=[('openai', 'OpenAI (GPT)'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google (Gemini)'), ('custom', 'Custom API')], default='openai', max_length=20, verbose_name='AI Provider')),
                ('api_key', models.CharField(help_text='AI provider API kaliti', max_length=500, verbose_name='API Key')),
                ('api_endpoint', models.URLField(blank=True, default='', help_text='Faqat Custom API uchun. Masalan: https://api.example.com/v1/chat', max_length=500, verbose_name='API Endpoint (Custom)')),
                ('model_name', models.CharField(default='gpt-4o-mini', help_text='Masalan: gpt-4o-mini, claude-3-5-sonnet-20241022, gemini-1.5-flash', max_length=100, verbose_name='Model nomi')),
                ('system_prompt', models.TextField(default="Siz mijozlar bilan operator suhbatlarini tahlil qiluvchi professional tahlilchisiz.\nSizning vazifangiz:\n1. Suhbat mazmunini tahlil qilish\n2. Operator xatti-harakatini baholash\n3. Mijoz qoniqish darajasini aniqlash\n4. Yaxshilash tavsiyalarini berish\n5. Muhim nuqtalarni ajratib ko'rsatish", help_text="AI ga beriladigan system (tizim) ko'rsatmasi", verbose_name='System Prompt')),
                ('analysis_prompt_template', models.TextField(default="Quyidagi telefon suhbatining matnini tahlil qil. \nMaqsad – operatorning mijozni ofisga chaqirishdagi natijaviyligini, SPIN texnikasi va Emotional Matching psixologik yondashuvini qay darajada to'g'ri qo'llaganini aniqlash.\n\nTahlilni quyidagi formatda yoz:\n\n1. UMUMIY BAHO (foizda):\n   Operatorning savdo samaradorligi, suhbatni boshqarish va mijozni ofisga olib kelishdagi umumiy natijasi (0–100%).\n\n2. BOSQICHLAR BO'YICHA TAHLIL:\n   1. Salomlashish va ishonch o'rnatish (0–10 + izoh)\n   2. Filtrlash - SPIN Situation (0–10 + izoh)\n   3. Ehtiyojni aniqlash - SPIN Problem + Implication (0–10 + izoh)\n   4. Qiymat yaratish - SPIN Need Payoff (0–10 + izoh)\n   5. Programmalashtirish va boshqaruv (0–10 + izoh)\n   6. Taqdimot (0–10 + izoh)\n   7. E'tirozlar bilan ishlash (0–10 + izoh)\n   8. Yakuniy bosqich - Sotuv yoki Keyingi qadam (0–10 + izoh)\n\n3. MIJOZ PSIXOLOGIK HOLATI:\n   - Kayfiyat: [ijobiy / betaraf / salbiy]\n   - Ishonch darajasi: (0–10)\n   - Xaridga tayyorlik foizi: (0–100%)\n\n4. EMOTSIONAL MATCHING KO'RSATKICHI (0–10)\n\n5. OPERATORNING KUCHLI TOMONLARI (3-4 ta)\n\n6. O'SISH NUQTALARI VA TAVSIYALAR\n\n7. QISQA XULOSA (2 jumla)\n\n8. UMUMIY BAHO: X/10\n\nQo'ng'iroq matni:\n{{text}}", help_text="{{text}} o'rniga suhbat matni qo'yiladi", verbose_name='Tahlil Prompt Shabloni')),
                ('max_tokens', models.IntegerField(default=4000, help_text='AI javobidagi maksimal tokenlar soni', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(32000)], verbose_name='Max Tokens')),
                ('temperature', models.FloatField(default=0.7, help_text='0.0 = aniq javob, 2.0 = ijodiy javob. Tavsiya: 0.5-0.8', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Temperature')),
                ('is_active', models.BooleanField(default=True, help_text='Faqat faol konfiguratsiyalar ishlatiladi', verbose_name='Faolmi')),
                ('is_default', models.BooleanField(default=False, help_text='Standart konfiguratsiya sifatida ishlatilsinmi', verbose_name='Standart')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operator AI Konfiguratsiya',
                'verbose_name_plural': 'Operator AI Konfiguratsiyalar',
                'ordering': ['-is_default', '-is_active', '-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='ai_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operators_analys.operatoraiconfiguration', verbose_name='Ishlatilgan AI config'),
        ),
    ]
