# Generated by Django 6.0.4 on 2026-04-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_url', models.URLField(help_text='Base URL: masalan https://megapolis1.uz/api/', verbose_name='CRM API URL')),
                ('username', models.CharField(max_length=255, verbose_name='CRM Username')),
                ('password', models.CharField(max_length=255, verbose_name='CRM Password')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='JWT Access Token')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='JWT Refresh Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token muddati')),
                ('is_connected', models.BooleanField(default=False, verbose_name='Ulanish holati')),
                ('last_connection_attempt', models.DateTimeField(auto_now=True, verbose_name='Oxirgi ulanish urinishi')),
                ('connection_error_message', models.TextField(blank=True, verbose_name="Agar xato bo'lsa, xabar")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CRM Configuration',
                'verbose_name_plural': 'CRM Configurations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
