# Generated by Django 6.0.4 on 2026-04-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmconfiguration',
            name='crm_url',
            field=models.URLField(blank=True, default='', help_text='Base URL: masalan https://megapolis1.uz/api/', null=True, verbose_name='CRM API URL'),
        ),
        migrations.AlterField(
            model_name='crmconfiguration',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='CRM Password'),
        ),
        migrations.AlterField(
            model_name='crmconfiguration',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='CRM Username'),
        ),
    ]
