# Generated by Django 6.0.4 on 2026-04-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_crmconfiguration_crm_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)')], default='anthropic', max_length=20, verbose_name='AI Provider')),
                ('api_key', models.CharField(blank=True, default='', help_text='Anthropic yoki OpenAI API kaliti', max_length=255, verbose_name='API Key')),
                ('model', models.CharField(default='claude-sonnet-4-20250514', help_text='Masalan: claude-sonnet-4-20250514, gpt-4o', max_length=100, verbose_name='AI Model')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
