# Generated by Django 6.0 on 2026-04-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aiconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='UzbekVoiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, default='', help_text='UzbekVoice.ai dan olingan API kalit (Authorization header uchun)', max_length=500, verbose_name='UzbekVoice API Key')),
                ('api_url', models.URLField(default='https://uzbekvoice.ai/api/v1/stt', help_text='UzbekVoice.ai STT API endpoint', max_length=500, verbose_name='API URL')),
                ('default_language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Rus'), ('ru-uz', "O'zbek-Rus (Aralash)")], default='uz', max_length=10, verbose_name='Default til')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UzbekVoice STT Configuration',
                'verbose_name_plural': 'UzbekVoice STT Configurations',
            },
        ),
    ]
