# Generated by Django 6.0.4 on 2026-04-12 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OLXProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olx_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='OLX ID')),
                ('url', models.URLField(max_length=500, verbose_name="E'lon URL")),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narx (USD)')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shahar')),
                ('address_text', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('rooms', models.IntegerField(blank=True, null=True, verbose_name='Xonalar soni')),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Umumiy maydon (m²)')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Qavat')),
                ('total_floors', models.IntegerField(blank=True, null=True, verbose_name='Umumiy qavatlar')),
                ('building_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qurilish turi')),
                ('repair_state', models.CharField(blank=True, max_length=100, null=True, verbose_name="Ta'mirlash holati")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Rasm URL')),
                ('is_processed', models.BooleanField(db_index=True, default=False, verbose_name='Qayta ishlangan')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name="Xom ma'lumot")),
            ],
            options={
                'verbose_name': "OLX E'lon",
                'verbose_name_plural': "OLX E'lonlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketPriceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etaj', models.IntegerField(db_index=True, verbose_name='Qavat raqami')),
                ('xonalar_soni', models.IntegerField(db_index=True, verbose_name='Xonalar soni')),
                ('qurilish_turi', models.CharField(choices=[('gishtli', 'Gʻishtli'), ('panelli', 'Panelli'), ('monolitli', 'Monolitli'), ('blokli', 'Blokli')], db_index=True, max_length=50, verbose_name='Qurilish turi')),
                ('holat', models.CharField(choices=[('remontli', 'Remontli'), ('remontsiz', 'Remontsiz')], db_index=True, max_length=20, verbose_name='Holat')),
                ('maydon_min', models.IntegerField(verbose_name='Minimal maydon (m²)')),
                ('maydon_max', models.IntegerField(blank=True, null=True, verbose_name='Maksimal maydon (m²)')),
                ('arzon_narx', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Arzon narx (so'm/m²)")),
                ('bozor_narx', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Bozor narxi (so'm/m²)")),
                ('qimmat_narx', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Qimmat narx (so'm/m²)")),
                ('source_file', models.CharField(blank=True, max_length=200, verbose_name='Qaysi fayldan')),
            ],
            options={
                'verbose_name': 'Bozor Narxi',
                'verbose_name_plural': 'Bozor Narxlari',
                'ordering': ['etaj', 'xonalar_soni', 'maydon_min'],
                'indexes': [models.Index(fields=['qurilish_turi', 'xonalar_soni'], name='market_anal_qurilis_354760_idx'), models.Index(fields=['etaj', 'holat'], name='market_anal_etaj_200553_idx')],
                'unique_together': {('etaj', 'xonalar_soni', 'qurilish_turi', 'holat', 'maydon_min')},
            },
        ),
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crm_object_id', models.IntegerField(db_index=True, verbose_name='CRM Obyekt ID')),
                ('crm_object_snapshot', models.JSONField(blank=True, default=dict, verbose_name='CRM obyekt snapshot')),
                ('similarity_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="O'xshashlik (%)")),
                ('price_difference_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narx farqi (USD)')),
                ('price_difference_percent', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Narx farqi (%)')),
                ('status', models.CharField(choices=[('cheaper', 'Arzonroq'), ('similar', "O'xshash"), ('expensive', 'Qimmatroq')], db_index=True, max_length=20, verbose_name='Status')),
                ('match_details', models.JSONField(blank=True, default=dict)),
                ('priority_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_notified', models.BooleanField(db_index=True, default=False)),
                ('olx_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='market_analys.olxproperty')),
            ],
            options={
                'verbose_name': 'Taqqoslash Natijasi',
                'verbose_name_plural': 'Taqqoslash Natijalari',
                'ordering': ['-priority_score', '-created_at'],
                'unique_together': {('olx_property', 'crm_object_id')},
            },
        ),
        migrations.CreateModel(
            name='PropertyPriceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.IntegerField(db_index=True, verbose_name='Obyekt ID')),
                ('property_type', models.CharField(choices=[('buildhouse', 'CRM Obyekt'), ('olxproperty', "OLX E'lon")], default='buildhouse', max_length=20, verbose_name='Obyekt turi')),
                ('status', models.CharField(choices=[('juda_arzon', 'Juda Arzon'), ('arzon', 'Arzon'), ('normal', 'Normal'), ('qimmat', 'Qimmat'), ('juda_qimmat', 'Juda Qimmat')], db_index=True, max_length=20, verbose_name='Status')),
                ('bozor_narxi', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Bozor narxi (USD/m²)')),
                ('joriy_narxi', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Hozirgi narx (USD/m²)')),
                ('farq_foiz', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Farq (foizda)')),
                ('farq_summa', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Farq (USD)')),
                ('ai_tahlil', models.TextField(blank=True, verbose_name='AI tahlil matni')),
                ('tavsiya', models.TextField(blank=True, verbose_name='AI tavsiyasi')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ishonch darajasi')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='Tahlil vaqti')),
                ('property_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Obyekt snapshot')),
                ('matched_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_analys.marketpricereference', verbose_name="Mos kelgan ma'lumotnoma")),
            ],
            options={
                'verbose_name': 'Narx Tahlili',
                'verbose_name_plural': 'Narx Tahillari',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['property_id', '-analyzed_at'], name='market_anal_propert_c6dcc7_idx'), models.Index(fields=['status'], name='market_anal_status_9402fd_idx'), models.Index(fields=['property_type', 'property_id'], name='market_anal_propert_a1590c_idx')],
            },
        ),
    ]
