# Generated by Django 5.2.8 on 2025-11-26 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_chat_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReplyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Qoida nomi', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_type', models.CharField(choices=[('keyword', "Kalit so'zlar"), ('all_messages', 'Barcha xabarlar'), ('first_message', 'Birinchi xabar'), ('command', 'Bot komandalar')], default='keyword', max_length=20)),
                ('keywords', models.TextField(blank=True, help_text="Kalit so'zlar (har birini yangi qatorda)")),
                ('reply_message', models.TextField(help_text='Javob xabari matni')),
                ('delay_seconds', models.IntegerField(default=0, help_text='Javob berishdan oldin kutish (soniya)')),
                ('reply_once_per_user', models.BooleanField(default=False, help_text='Har bir userga faqat 1 marta javob')),
                ('work_hours_only', models.BooleanField(default=False, help_text='Faqat ish vaqtida ishlash')),
                ('work_hours_start', models.TimeField(blank=True, help_text='Ish boshlanish vaqti', null=True)),
                ('work_hours_end', models.TimeField(blank=True, help_text='Ish tugash vaqti', null=True)),
                ('excluded_users', models.TextField(blank=True, help_text='Javob bermaslik kerak userlar (username yoki user_id, har birini yangi qatorda)')),
                ('only_private_chats', models.BooleanField(default=True, help_text='Faqat shaxsiy chatlarda ishlash')),
                ('messages_sent_count', models.IntegerField(default=0, help_text='Yuborilgan javoblar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_reply_rules', to='home.telegramaccount')),
            ],
            options={
                'verbose_name': 'Auto Reply Rule',
                'verbose_name_plural': 'Auto Reply Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoReplyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('trigger_message', models.TextField(help_text='Javob trigger qilgan xabar')),
                ('reply_sent', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='home.autoreplyrule')),
            ],
            options={
                'verbose_name': 'Auto Reply Log',
                'verbose_name_plural': 'Auto Reply Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
