# Generated by Django 5.2.8 on 2025-11-26 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_autoreplyrule_mark_as_read_autoreplyrule_show_typing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Provider nomi (masalan: 'My OpenAI Key')", max_length=100)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI (GPT)'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google (Gemini)'), ('custom', 'Custom API')], default='openai', max_length=20)),
                ('api_key', models.CharField(help_text='API kalit', max_length=500)),
                ('api_endpoint', models.URLField(blank=True, help_text="Custom API endpoint (agar kerak bo'lsa)", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Assistant nomi', max_length=100)),
                ('model', models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'), ('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku'), ('claude-3-opus-20240229', 'Claude 3 Opus'), ('gemini-2.0-flash-exp', 'Gemini 2.0 Flash'), ('gemini-1.5-pro', 'Gemini 1.5 Pro'), ('custom', 'Custom Model')], default='gpt-4o-mini', max_length=100)),
                ('system_prompt', models.TextField(default='You are a helpful AI assistant for Telegram messages. Be concise and friendly.', help_text='AI assistant uchun system prompt')),
                ('is_active', models.BooleanField(default=True, help_text='AI assistant faolmi?')),
                ('auto_respond', models.BooleanField(default=True, help_text='Avtomatik javob beradimi?')),
                ('only_private_chats', models.BooleanField(default=True, help_text='Faqat shaxsiy chatlarda ishlasin')),
                ('response_delay_seconds', models.IntegerField(default=2, help_text='Javob berishdan oldin kutish vaqti')),
                ('mark_as_read', models.BooleanField(default=True, help_text="Xabarni o'qilgan deb belgilash")),
                ('show_typing', models.BooleanField(default=True, help_text="Typing indicator ko'rsatish")),
                ('typing_duration', models.IntegerField(default=3, help_text='Typing davomiyligi (soniya)')),
                ('messages_processed', models.IntegerField(default=0, help_text='Qayta ishlangan xabarlar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistants', to='home.telegramaccount')),
                ('ai_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='home.aiprovider')),
            ],
            options={
                'verbose_name': 'AI Assistant',
                'verbose_name_plural': 'AI Assistants',
                'ordering': ['-created_at'],
                'unique_together': {('telegram_account', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(help_text='Telegram chat ID')),
                ('user_id', models.BigIntegerField(blank=True, help_text='Telegram user ID', null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('summary_data', models.JSONField(blank=True, default=dict, help_text='Suhbat xulosasi JSON formatda')),
                ('last_message_at', models.DateTimeField(auto_now=True, help_text='Oxirgi xabar vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='home.aiassistant')),
                ('telegram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_summaries', to='home.telegramaccount')),
            ],
            options={
                'verbose_name': 'Conversation Summary',
                'verbose_name_plural': 'Conversation Summaries',
                'ordering': ['-last_message_at'],
                'unique_together': {('telegram_account', 'ai_assistant', 'chat_id')},
            },
        ),
    ]
