# Generated by Django 5.2.8 on 2025-11-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_aiassistant_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsummary',
            name='context_window_size',
            field=models.IntegerField(default=20, help_text="Context window size (o'zgartirish mumkin)"),
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='last_ai_message',
            field=models.TextField(blank=True, help_text='Oxirgi AI xabari', null=True),
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='last_interaction_at',
            field=models.DateTimeField(auto_now=True, help_text="Oxirgi o'zaro ta'sir"),
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='last_summary_at',
            field=models.DateTimeField(blank=True, help_text='Oxirgi summary yangilangan vaqt', null=True),
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='last_user_message',
            field=models.TextField(blank=True, help_text='Oxirgi user xabari', null=True),
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='message_count',
            field=models.IntegerField(default=0, help_text='Jami xabarlar soni'),
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='messages_since_summary',
            field=models.IntegerField(default=0, help_text='Summary yaratilganidan keyingi xabarlar'),
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='needs_reply',
            field=models.BooleanField(default=False, help_text='Javob kerakmi?'),
        ),
    ]
